import * as Phaser from 'phaser';
import {FIGHTERS,STAGE,fighter,asset,damageColor,ITEMS,type Settings,type MatchConfig,type Animation} from './data';
import {Simulation,type Actor,type CombatEvent} from './simulation';import {InputController} from './input';import {GameAudio} from './audio';
type Atlas={width:number;height:number;frames:number;bounds:{x:number;y:number;w:number;h:number}};
type Manifest=Record<string,Record<string,Atlas>>;
export interface GameBridge {sim:Simulation|null;input:InputController|null;paused:boolean;debug:boolean;settings:Settings;onUpdate:(sim:Simulation)=>void;onReady:()=>void;onError:(message:string)=>void;onPause:()=>void;audio:GameAudio|null}
export function launchGame(parent:HTMLElement,config:MatchConfig,bridge:GameBridge){
 class ArenaScene extends Phaser.Scene {
  sim!:Simulation;acc=0;manifest!:Manifest;sprites:Phaser.GameObjects.Sprite[]=[];labels:Phaser.GameObjects.Text[]=[];gfx!:Phaser.GameObjects.Graphics;fx!:Phaser.GameObjects.Graphics;back!:Phaser.GameObjects.Graphics;debugText!:Phaser.GameObjects.Text;particles:{x:number;y:number;vx:number;vy:number;life:number;max:number;size:number;color:number}[]=[];rings:{x:number;y:number;life:number;max:number;color:number;size:number}[]=[];zoomFactor=1;frameAvg=16;lastEmit=-1;
  constructor(){super('Arena');}
  preload(){this.load.image('planet',asset('planet.png'));this.load.json('manifest',asset('manifest.json'));this.load.once('filecomplete-json-manifest',(_k:string,_t:string,data:Manifest)=>{this.manifest=data;for(const f of FIGHTERS)for(const [anim,meta] of Object.entries(data[f.id]))this.load.spritesheet(`${f.id}-${anim}`,asset(`fighters/${f.id}/${anim}.png`),{frameWidth:meta.width,frameHeight:meta.height});});this.load.on('loaderror',()=>bridge.onError('A game asset could not load. Check your connection and retry.'));}
  create(){this.sim=new Simulation(config);bridge.sim=this.sim;bridge.input=new InputController(bridge.settings,()=>bridge.onPause(),()=>{bridge.debug=!bridge.debug;});bridge.audio=new GameAudio(bridge.settings);void bridge.audio.start();bridge.input.onGesture=()=>{void bridge.audio?.start();};this.back=this.add.graphics().setDepth(-10);this.gfx=this.add.graphics();this.fx=this.add.graphics().setDepth(20);this.debugText=this.add.text(10,10,'',{fontFamily:'monospace',fontSize:'13px',color:'#ffffff',backgroundColor:'#000c'}).setScrollFactor(0).setDepth(100);
   for(const a of this.sim.actors){const def=fighter(a.slot.fighter);this.sprites.push(this.add.sprite(a.x,a.y,`${def.id}-idle`).setDepth(5));this.labels.push(this.add.text(0,0,a.id===0?'▼ YOU':`CPU ${a.id}`,{fontFamily:'monospace',fontSize:'13px',fontStyle:'bold',color:def.color}).setOrigin(.5,1).setDepth(8));}
   this.add.image(500,245,'planet').setDisplaySize(330,330).setAlpha(.23).setTint(0xaaaaff).setDepth(-9);this.drawBackground();this.scale.on('resize',()=>this.drawBackground());bridge.onReady();bridge.onUpdate(this.sim);
   if(new URLSearchParams(location.search).has('debug')){(window as unknown as {rift:unknown}).rift={simulation:this.sim,bridge};}
  }
  drawBackground(){const g=this.back;g.clear();g.fillGradientStyle(0x090e22,0x110c25,0x131b35,0x141831,1);g.fillRect(-1200,-1300,3500,3000);g.lineStyle(1,0x6576a5,.09);for(let x=-600;x<1700;x+=80)g.lineBetween(x,-600,x,1400);for(let y=-600;y<1400;y+=80)g.lineBetween(-600,y,1700,y);
   // Abstract dimensional aperture, never a gameplay obstacle.
   for(let i=0;i<6;i++){g.lineStyle(i%2?1:2,i%2?0x27e8ed:0xff58b1,.07+i*.013);g.strokeCircle(500,270,120+i*42);}g.lineStyle(1,0x27e8ed,.22);g.strokeEllipse(500,290,850,170);g.lineStyle(2,0xff58b1,.13);g.strokeEllipse(500,300,380,720);
   let seed=235;for(let i=0;i<150;i++){seed=(seed*16807)%2147483647;const x=seed%1800-400;seed=(seed*16807)%2147483647;const y=seed%1600-600;g.fillStyle(i%3===0?0x27e8ed:0xcbd8ff,.15+(i%4)*.12);g.fillRect(x,y,i%8===0?3:1,i%8===0?3:1);}
  }
  update(_time:number,delta:number){if(!this.sim)return;this.frameAvg=this.frameAvg*.95+delta*.05;if(bridge.input)bridge.input.settings=bridge.settings;if(bridge.audio)bridge.audio.settings=bridge.settings;
   if(!bridge.paused&&!this.sim.ended){this.acc+=Math.min(delta,100);let steps=0;while(this.acc>=1000/60&&steps++<6){this.sim.step(bridge.input?.sample());for(const e of this.sim.events)this.effect(e);this.acc-=1000/60;}bridge.audio?.music(this.sim.tick);if(this.sim.tick%6===0||this.sim.ended)bridge.onUpdate(this.sim);}else this.acc=0;
   this.renderWorld(Math.min(1,this.acc/(1000/60)),bridge.paused?0:Math.min(delta/16.67,3));
  }
  effect(e:CombatEvent){if(e.kind==='ko'){const view=this.cameras.main.worldView;e={...e,x:Phaser.Math.Clamp(e.x,view.left+60,view.right-60),y:Phaser.Math.Clamp(e.y,view.top+100,view.bottom-60)};const id=this.sim.actors[e.actor].slot.fighter;const ghost=this.add.sprite(e.x,e.y,`${id}-death`).setScale(1.3).setTintFill(0xffffff).setDepth(19);this.tweens.addCounter({from:0,to:this.manifest[id].death.frames-1,duration:400,onUpdate:t=>{ghost.setFrame(Math.floor(t.getValue()??0));ghost.setAlpha(1-t.progress);},onComplete:()=>ghost.destroy()});}const col=Phaser.Display.Color.HexStringToColor(e.kind==='hit'?damageColor(this.sim.actors[e.actor].damage):e.color).color;
   if(['hit','ko','jump','dodge','item','respawn'].includes(e.kind))bridge.audio?.play(e.kind,e.power);
   const count=e.kind==='ko'?65:e.kind==='hit'?14:e.kind==='item'?22:7;const budget=this.frameAvg>23?80:220;
   for(let i=0;i<count&&this.particles.length<budget;i++){const angle=Math.random()*Math.PI*2,speed=(Math.random()+.2)*(e.kind==='ko'?13:e.kind==='hit'?5:2);this.particles.push({x:Phaser.Math.Clamp(e.x,-20,1020),y:Phaser.Math.Clamp(e.y,-50,850),vx:Math.cos(angle)*speed,vy:Math.sin(angle)*speed,life:30+Math.random()*20,max:50,size:e.kind==='ko'?6+Math.random()*12:2+Math.random()*5,color:i%3===0?0xffffff:col});}
   if(['ko','hit','dodge','jump','respawn','item'].includes(e.kind))this.rings.push({x:Phaser.Math.Clamp(e.x,-20,1020),y:Phaser.Math.Clamp(e.y,-50,850),life:20,max:20,color:col,size:e.kind==='ko'?190:e.kind==='respawn'?65:e.kind==='hit'?35:25});
   if(e.kind==='ko'){if(bridge.settings.shake)this.cameras.main.shake(220,.006);if(bridge.settings.flashes)this.cameras.main.flash(100,40,220,235,false);}
   else if(e.kind==='hit'&&e.power>13&&bridge.settings.shake)this.cameras.main.shake(85,.0025);
  }
  renderWorld(alpha:number,dt:number){const sim=this.sim,g=this.gfx,fx=this.fx;g.clear();fx.clear();const alive=sim.actors.filter(a=>!a.out&&!a.respawn);const minX=Math.min(250,...alive.map(a=>a.x)),maxX=Math.max(750,...alive.map(a=>a.x));const desired=Phaser.Math.Clamp(950/(maxX-minX+260),.8,1.12);this.zoomFactor+=(desired-this.zoomFactor)*.035;
   const cam=this.cameras.main;const base=Math.min(this.scale.width/1000,this.scale.height/720);cam.setZoom(base*this.zoomFactor);cam.centerOn(500,470);
   for(const [i,p] of STAGE.platforms.entries()){g.fillStyle(0x27e8ed,.025);g.fillRect(p.x-12,p.y-4,p.width+24,75);g.fillStyle(i?0x20283e:0x151c2d,1);g.fillRect(p.x,p.y,p.width,i?22:56);g.fillStyle(0x354663);g.fillRect(p.x,p.y+3,p.width,4);g.lineStyle(2,i?0xff58b1:0x27e8ed,.9);g.lineBetween(p.x,p.y,p.x+p.width,p.y);g.fillStyle(0xffe45b,.7);for(let x=p.x+15;x<p.x+p.width-5;x+=60)g.fillRect(x,p.y+12,18,3);g.lineStyle(1,0x556079,.4);for(let x=p.x;x<p.x+p.width;x+=80)g.lineBetween(x,p.y+9,x+40,p.y+44);g.fillStyle(0x090e1c);g.fillTriangle(p.x,p.y+56,p.x+90,p.y+56,p.x+70,p.y+95);g.fillTriangle(p.x+p.width,p.y+56,p.x+p.width-90,p.y+56,p.x+p.width-70,p.y+95);}
   for(const a of sim.actors){const sprite=this.sprites[a.id],label=this.labels[a.id],def=fighter(a.slot.fighter);if(a.out||a.respawn){sprite.setVisible(false);label.setVisible(false);continue;}sprite.setVisible(true);label.setVisible(true);const x=a.px+(a.x-a.px)*alpha,y=a.py+(a.y-a.py)*alpha;
    let anim:Animation=a.stun>0?'hurt':a.move?a.move.animation:!a.grounded?(a.vy<0?'jump':'fall'):Math.abs(a.vx)>.8?'run':'idle';if(a.dodgeTime>0)anim='jump';const meta=this.manifest[def.id][anim],idle=this.manifest[def.id].idle;const scale=def.id==='omen'?1.15:def.id==='kairo'?1.6:def.id==='regent'?1.4:1.55;
    const baseline=def.id==='kairo'?(anim==='jump'||anim==='fall'?95:81):def.id==='regent'?104:def.id==='vexa'?96:166;
    sprite.setTexture(`${def.id}-${anim}`);let frame=Math.floor(sim.tick/(anim==='run'?5:8))%meta.frames;if(a.move){const m=a.move;const t=a.moveTick<m.startup?(a.moveTick/m.startup)*.32:a.moveTick<m.startup+m.active?.32+(a.moveTick-m.startup)/m.active*.38:.7+(a.moveTick-m.startup-m.active)/m.recovery*.3;frame=Math.min(meta.frames-1,Math.floor(t*meta.frames));}else if(anim==='jump'||anim==='fall')frame=Math.min(meta.frames-1,Math.floor(Math.abs(a.vy)/7));
    sprite.setFrame(frame).setOrigin(.5,(baseline+1)/meta.height).setPosition(x,y).setFlipX(a.face<0).setScale(scale*(a.landing?1.08:1),scale*(a.landing?.88:1));sprite.setAngle(a.stun>0?Phaser.Math.Clamp(a.vx*1.8,-30,30):a.dodgeTime?Math.sin(a.dodgeAge*.5)*15:0);sprite.setAlpha(a.invulnerable>0?(sim.tick%12<6?.5:1):a.dodgeTime?.45:1);sprite.clearTint();if(a.freeze>0&&bridge.settings.flashes)sprite.setTintFill(0xffffff);
    const color=Phaser.Display.Color.HexStringToColor(def.color).color;g.fillStyle(color,.12);g.fillEllipse(x,STAGE.platforms[a.platform]?.y??610,def.width*2.4,8);label.setPosition(x,y-def.height-18);label.setText(a.id===0?'▼ YOU':`CPU ${a.id}`);label.setColor(bridge.settings.contrast?'#ffffff':this.sim.config.teams?(a.slot.team===0?'#27e8ed':'#ff58b1'):def.color);
    if(a.id===0){g.lineStyle(2,color,.75);for(let n=0;n<a.airJumps;n++)g.strokeCircle(x-7+n*14,y+13,3);if(!a.recoveryUsed){g.fillStyle(color,.7);g.fillRect(x-3,y+20,6,2);}}
    if(a.stun>0&&Math.hypot(a.vx,a.vy)>7&&dt>0&&sim.tick!==this.lastEmit){this.particles.push({x:x-a.vx,y:y-def.height*.5,vx:0,vy:-.3,life:23,max:23,size:6+Math.min(a.damage/20,8),color:Phaser.Display.Color.HexStringToColor(damageColor(a.damage)).color});}
    if(a.dodgeTime>0){g.lineStyle(2,color,.7);g.strokeEllipse(x,y-def.height/2,def.width+25,def.height+15);}
    if(a.move){const m=a.move,b=m.hitbox;if(a.moveTick>=m.startup&&a.moveTick<m.startup+m.active&&!m.projectile){const centerX=x+b.x*a.face,centerY=y+b.y;g.lineStyle(5,color,.7);g.beginPath();const start=a.face>0?-1.4:1.7;g.arc(centerX,centerY,b.radius,start,start+2.6);g.strokePath();g.lineStyle(2,0xffffff,.9);g.beginPath();g.arc(centerX,centerY,b.radius*.8,start+.2,start+2.2);g.strokePath();}if(a.charge>0){g.lineStyle(2,0xffe45b,.8);g.strokeCircle(x,y-30,35+a.charge*.4);}}
    if(bridge.debug){g.lineStyle(1,0x00ff66,.8);g.strokeRoundedRect(x-def.width/2,y-def.height,def.width,def.height,def.width/2);g.lineStyle(1,0xff3333);if(a.move){const b=a.move.hitbox;g.strokeCircle(x+b.x*a.face,y+b.y,b.radius);g.lineBetween(x+b.x*a.face,y+b.y,x+(b.endX??b.x)*a.face,y+(b.endY??b.y));}g.lineStyle(2,0xffe45b);g.lineBetween(x,y,x+a.vx*5,y+a.vy*5);}
   }
   this.lastEmit=sim.tick;
   for(const p of sim.projectiles){const c=Phaser.Display.Color.HexStringToColor(fighter(sim.actors[p.owner].slot.fighter).color).color;g.fillStyle(c,p.arm>0?.15:.75);if(p.kind==='mine'||p.kind==='sigil'){g.fillEllipse(p.x,p.y,p.radius*2,p.arm>0?8:28);g.lineStyle(2,c,.8);g.strokeEllipse(p.x,p.y,p.radius*2+8,12);}else{g.fillCircle(p.x,p.y,p.radius);g.fillStyle(0xffffff,.8);g.fillCircle(p.x,p.y,p.radius*.4);g.lineStyle(p.radius,c,.2);g.lineBetween(p.x,p.y,p.x-p.vx*3,p.y-p.vy*3);}}
   for(const it of sim.items){const col=ITEMS[it.kind].color;g.fillStyle(col,.14);g.fillCircle(it.x,it.y,22);g.lineStyle(2,col,1);g.strokeCircle(it.x,it.y,12);g.fillStyle(col,1);if(it.kind==='repair'){g.fillRect(it.x-7,it.y-2,14,4);g.fillRect(it.x-2,it.y-7,4,14);}else if(it.kind==='spike'){g.fillTriangle(it.x,it.y-9,it.x-8,it.y+7,it.x+8,it.y+7);}else {g.fillCircle(it.x,it.y,7);g.lineStyle(2,0xffffff,it.fuse>0&&sim.tick%12<6?1:.3);g.lineBetween(it.x+4,it.y-6,it.x+10,it.y-13);}}
   for(const p of this.particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.98;p.vy+=.035*dt;fx.fillStyle(p.color,Math.max(0,p.life/p.max)*.7);fx.fillRect(p.x,p.y,p.size,p.size*.55);}this.particles=this.particles.filter(p=>p.life>0).slice(-250);
   for(const r of this.rings){r.life-=dt;const t=1-r.life/r.max;fx.lineStyle(2,r.color,Math.max(0,1-t));fx.strokeCircle(r.x,r.y,r.size*t);if(r.size>100){for(let i=0;i<6;i++){fx.fillStyle([0x27e8ed,0xff58b1,0xffe45b][i%3],(1-t)*.65);fx.fillRect(r.x-r.size+t*200+i*9,r.y+(i-3)*25,r.size*2*(1-t),4+i);}}}this.rings=this.rings.filter(r=>r.life>0);
   this.debugText.setVisible(bridge.debug);if(bridge.debug)this.debugText.setText([`60 Hz | tick ${sim.tick} | ${Math.round(1000/this.frameAvg)} FPS`,...sim.actors.map(a=>`${a.id} ${a.move?.id??(a.stun?'stun':'idle')} ${a.moveTick} J${a.airJumps} R${!a.recoveryUsed} D${a.dodgeCD} ${a.aiIntent}`)]);
  }
 }
 return new Phaser.Game({type:Phaser.AUTO,parent,backgroundColor:'#0b1021',pixelArt:true,roundPixels:false,antialias:false,scale:{mode:Phaser.Scale.RESIZE,width:parent.clientWidth,height:parent.clientHeight},scene:ArenaScene,audio:{noAudio:true},render:{powerPreference:'high-performance'},fps:{target:60,smoothStep:false},banner:false});
}
