import test from 'node:test';import assert from 'node:assert/strict';
import {Simulation} from '../game/simulation';import {defaultConfig,FIGHTERS,emptyInput,type InputFrame} from '../game/data';
function setup(){const s=new Simulation({...defaultConfig,items:'off'});s.countdown=0;return s;}
for(const f of FIGHTERS)for(const move of Object.values(f.moves))for(const face of [-1,1])test(`${f.id}/${move.id} facing ${face}: authored active geometry and ownership`,()=>{
 const s=setup(),a=s.actors[0],b=s.actors[1];a.slot.fighter=f.id;a.x=500;a.y=500;a.face=face;a.move=move;a.moveTick=move.startup;a.hit.clear();
 if(move.projectile){s.spawnProjectile(a,move);const p=s.projectiles[0];p.arm=0;b.x=p.x+p.vx;b.y=p.y+30;s.stepProjectiles();const damage=b.damage;s.stepProjectiles();assert(damage>0);assert.equal(b.damage,damage);assert.equal(a.damage,0);}
 else {b.x=a.x+move.hitbox.x*face;b.y=a.y+move.hitbox.y+30;s.resolveAttack(a);const damage=b.damage;assert(damage>0);assert.equal(a.damage,0);s.resolveAttack(a);assert.equal(b.damage,damage);}
});
test('DI rotates by at most 18 degrees once and preserves launch speed',()=>{const s=setup(),a=s.actors[0];a.y=300;a.grounded=false;a.vx=15;a.vy=0;a.stun=20;a.freeze=8;a.diApplied=false;s.stepActor(a,{...emptyInput(),y:-1});assert(Math.abs(Math.atan2(a.vy,a.vx))<=Math.PI/10+.00001);assert(Math.abs(Math.hypot(a.vx,a.vy)-15)<.001);const angle=Math.atan2(a.vy,a.vx);s.stepActor(a,{...emptyInput(),y:1});assert.equal(Math.atan2(a.vy,a.vx),angle);});
test('six-frame buffered attack survives final recovery frames',()=>{const s=setup(),a=s.actors[0];a.move=FIGHTERS[0].moves.nl;a.moveTick=a.move.startup+a.move.active+a.move.recovery-3;for(let n=0;n<5;n++)s.step(emptyInput(),[{...emptyInput(),heavy:n===0},emptyInput()]);assert.equal(a.move?.id,'nh');});
test('a fast projectile cannot tunnel through a body',()=>{const s=setup(),a=s.actors[0],b=s.actors[1];a.slot.fighter='omen';a.x=200;b.x=500;s.spawnProjectile(a,FIGHTERS[3].moves.sl);const p=s.projectiles[0];p.x=300;p.y=580;p.vx=400;s.stepProjectiles();assert(b.damage>0);});
test('timed team score sums team members, not individual leaders',()=>{const s=new Simulation({...defaultConfig,mode:'timed',teams:true,slots:FIGHTERS.map((f,i)=>({fighter:f.id,difficulty:'medium',team:i%2}))});s.actors[0].score=4;s.actors[2].score=4;s.actors[1].score=7;s.resolveTime();assert(s.ended);assert.deepEqual(s.winners,[0,2]);});
test('wall contact restores resources but has a finite chain limit',()=>{const s=setup(),a=s.actors[0];a.x=140;a.px=140;a.y=650;a.grounded=false;a.vx=10;a.airJumps=0;a.recoveryUsed=true;s.stepActor(a,{...emptyInput(),x:1});assert.equal(a.airJumps,2);assert.equal(a.recoveryUsed,false);assert(a.wallUses>0);});
test('fast fall accelerates descent and landing resets resources',()=>{const s=setup(),a=s.actors[0];a.y=500;a.grounded=false;a.vy=5;const v=a.vy;s.stepActor(a,{...emptyInput(),y:1});assert(a.vy>v+FIGHTERS[0].gravity);a.airJumps=0;a.recoveryUsed=true;for(let n=0;n<30;n++)s.stepActor(a,emptyInput());assert(a.grounded);assert.equal(a.airJumps,2);assert(!a.recoveryUsed);});
test('air dodge cooldown cannot be reset by a second dodge input',()=>{const s=setup(),a=s.actors[0];a.y=300;a.grounded=false;s.stepActor(a,{...emptyInput(),dodge:true,x:1,y:-1});assert.equal(a.dodgeCD,130);for(let n=0;n<15;n++)s.stepActor(a,emptyInput());const cd=a.dodgeCD;s.stepActor(a,{...emptyInput(),dodge:true});assert.equal(a.dodgeCD,cd-1);assert.equal(a.dodgeTime,0);});
