import test from 'node:test';
import assert from 'node:assert/strict';
import type {DataConnection} from 'peerjs';
import {MultiplayerRoom} from '../game/multiplayer';
import {cleanName,createRoomCode,validRoomCode,inviteURL,roomCode,InputMailbox,inputSchema,captureSnapshot,applySnapshot,snapshotSchema,NETWORK_VERSION} from '../game/network-protocol';
import {Simulation} from '../game/simulation';
import {defaultConfig,emptyInput} from '../game/data';

test('Starting a rematch resets input sequencing without accepting old-epoch packets',()=>{const room=host(),{c}=join(room,'guest');room.state.members[1].ready=true;room.mailboxes.get('guest')!.receive(900,emptyInput(),performance.now());room.start();const match=room.match;room.ready();room['receiveGuest'](c,{type:'loaded',match});room['receiveGuest'](c,{type:'input',match,sequence:0,input:{...emptyInput(),x:1}});assert.equal(room.inputs(emptyInput())[1].x,1);room['receiveGuest'](c,{type:'input',match:'previous-round',sequence:1000,input:{...emptyInput(),x:-1}});assert.equal(room.inputs(emptyInput())[1].x,1);room.destroy();});

function host(){const room=new MultiplayerRoom(true,'Host','kairo');room.id='host';room.state.phase='lobby';room.state.members=[{id:'host',name:'Host',fighter:'kairo',difficulty:'medium',team:0,cpu:false,ready:true}];room.addCPU();return room;}
function connection(id:string){const messages:unknown[]=[];const c={peer:id,open:true,dataChannel:{bufferedAmount:0},send:(data:unknown)=>messages.push(data),close:()=>{}} as unknown as DataConnection;return {c,messages};}

test('Older dodge-rule clients receive a clear refresh instruction',()=>{const room=host(),{c,messages}=connection('old-client');room['receiveGuest'](c,{type:'hello',version:NETWORK_VERSION-1,name:'Old client',fighter:'kairo'});assert.match(JSON.stringify(messages),/Refresh on every device/);assert.equal(room.state.members.some(m=>m.id==='old-client'),false);room.destroy();});
function join(room:MultiplayerRoom,id:string){const link=connection(id);room.connections.set(id,link.c);room['receiveGuest'](link.c,{type:'hello',version:NETWORK_VERSION,name:id,fighter:'vexa'});return link;}

test('Room codes are cryptographically generated, bounded, and invite fragments round trip',()=>{const codes=new Set(Array.from({length:100},()=>createRoomCode()));assert.equal(codes.size,100);for(const code of codes){assert(validRoomCode(code));const url=new URL(inviteURL('https://example.com/rift-breakers/?debug#old',code));assert.equal(url.pathname,'/rift-breakers/');assert.equal(url.search,'');assert.equal(new URLSearchParams(url.hash.slice(1)).get('room'),code);}assert.equal(roomCode('abcd-efgh 2345'),'ABCDEFGH2345');assert(!validRoomCode('<script>'));});
test('Names have no control/directional override characters and retain whole Unicode characters',()=>{assert.equal(cleanName('  Nova\n   Star\u202e '),'Nova Star');assert.equal(cleanName('   '),'Rift player');assert.equal(cleanName('x'.repeat(200)).length,16);assert.equal(cleanName('🚀'.repeat(16)), '🚀'.repeat(8));});
test('Input packets cannot carry invalid axes, nonfinite physics or hidden bonuses',()=>{assert(!inputSchema.safeParse({...emptyInput(),x:2}).success);assert(!inputSchema.safeParse({...emptyInput(),y:NaN}).success);assert.deepEqual(inputSchema.parse({...emptyInput(),damage:999}),emptyInput());});
test('Mailbox retains short taps, rejects replays and expires stale held controls',()=>{const box=new InputMailbox();assert(box.receive(1,{...emptyInput(),light:true,x:1},10));assert(box.receive(2,emptyInput(),20));assert(box.sample(30).light);assert(!box.sample(31).light);assert(!box.receive(1,{...emptyInput(),heavy:true},40));assert(box.receive(3,{...emptyInput(),x:1},50));assert.equal(box.sample(60).x,1);assert.deepEqual(box.sample(401),emptyInput());});
test('Snapshot round trip uses authoritative state, move definitions, projectiles and scores',()=>{const config=structuredClone(defaultConfig),a=new Simulation(config),b=new Simulation(config);a.countdown=0;for(let i=0;i<8;i++)a.step({...emptyInput(),light:i===0});a.spawnItem('spike');a.actors[0].damage=72;a.actors[1].score=2;const packet=captureSnapshot(a,a.events,false);assert(snapshotSchema.safeParse(JSON.parse(JSON.stringify(packet))).success);assert(applySnapshot(b,packet));assert.equal(b.tick,a.tick);assert.equal(b.actors[0].damage,72);assert.equal(b.actors[0].move?.id,a.actors[0].move?.id);assert.equal(b.actors[1].score,2);assert.deepEqual(b.items,a.items);assert(b.actors[0].hit instanceof Set);});
test('Snapshots reject NaN, huge geometry, missing fighters and invalid owner references',()=>{const sim=new Simulation(defaultConfig),snapshot=captureSnapshot(sim,[],false);assert(!snapshotSchema.safeParse({...snapshot,actors:[{...snapshot.actors[0],x:Infinity}]}).success);assert(!snapshotSchema.safeParse({...snapshot,actors:[{...snapshot.actors[0],x:1e50},snapshot.actors[1]]}).success);assert(!applySnapshot(sim,{...snapshot,actors:[snapshot.actors[0]]}));assert(!applySnapshot(sim,{...snapshot,actors:[{...snapshot.actors[0],id:1},snapshot.actors[1]]}));assert(!applySnapshot(sim,{...snapshot,events:[{kind:'hit',x:0,y:0,color:'#ffffff',power:1,actor:3}]}));});
test('Humans replace CPU slots, room capacity is four, fifth human is rejected',()=>{const room=host();join(room,'one');join(room,'two');join(room,'three');assert.equal(room.state.members.length,4);assert(room.state.members.every(m=>!m.cpu));const extra=join(room,'four');assert.equal(room.state.members.length,4);assert(extra.messages.some(m=>(m as {type:string}).type==='reject'));room.destroy();});
test('Only the assigned connection can submit input; invalid phase and epoch are ignored',()=>{const room=host(),{c}=join(room,'guest');room.state.phase='playing';room.match='epoch';room.matchIds=['host','guest'];room['receiveGuest'](c,{type:'input',match:'old',sequence:0,input:{...emptyInput(),x:1}});assert.equal(room.inputs(emptyInput())[1].x,0);room['receiveGuest'](c,{type:'input',match:'epoch',sequence:1,input:{...emptyInput(),x:1},slot:0});assert.equal(room.inputs(emptyInput())[0].x,0);assert.equal(room.inputs(emptyInput())[1].x,1);room.destroy();});
test('Readiness, team opponents, asset loading and host authority gate match start',()=>{const room=host(),{c}=join(room,'guest');assert(!room.canStart());room['receiveGuest'](c,{type:'profile',name:'guest',fighter:'vexa',ready:true});assert(room.canStart());room.setRules({teams:true});assert(!room.canStart());room['receiveGuest'](c,{type:'profile',name:'guest',fighter:'vexa',ready:true});room.setMember('guest',{team:0});room['receiveGuest'](c,{type:'profile',name:'guest',fighter:'vexa',ready:true});assert(!room.canStart());room.setMember('guest',{team:1});room['receiveGuest'](c,{type:'profile',name:'guest',fighter:'vexa',ready:true});let starts=0;room.onStart=()=>starts++;room.start();assert.equal(starts,1);assert.equal(room.state.phase,'loading');room.ready();assert.equal(room.state.phase,'loading');room['receiveGuest'](c,{type:'loaded',match:room.match});assert.equal(room.state.phase,'playing');room.destroy();const guest=new MultiplayerRoom(false,'Guest','omen','ABCDEFGH2345');guest.start();guest.addCPU();guest.setRules({stocks:5});assert.equal(guest.state.members.length,0);assert.equal(guest.state.phase,'connecting');guest.destroy();});
test('Disconnected guest becomes a CPU without changing fighter indexes; rematch resets ready flags',()=>{const room=host();join(room,'guest');room.state.phase='playing';room.matchIds=['host','guest'];room['depart']('guest');assert.equal(room.state.members[1].cpu,true);assert.equal(room.inputs(emptyInput())[1],undefined);room.backToLobby();assert.equal(room.state.phase,'lobby');assert.equal(room.state.members.length,2);assert.equal(room.match,'');room.destroy();});
test('Guest rejects mismatched match snapshots and ignores unrelated start assignment',()=>{const room=new MultiplayerRoom(false,'Guest','omen','ABCDEFGH2345');room.id='guest';room.match='current';const {c}=connection('host'),s=new Simulation(defaultConfig);room['receiveHost'](c,{type:'frame',match:'stale',state:captureSnapshot(s,[],false)});assert.equal(room.latest,null);room['receiveHost'](c,{type:'frame',match:'current',state:captureSnapshot(s,[],false)});assert.deepEqual(room.latest,captureSnapshot(s,[],false));room.destroy();});
