import {readFileSync,writeFileSync} from 'node:fs';
import {CUES} from '../game/audio-catalog.ts';
const m=JSON.parse(readFileSync('public/assets/audio/manifest.json','utf8'));
const text=[
'# RIFT//BREAKERS — recorded audio guide',
'',
'## Mix direction',
'',
'Movement is intentionally restrained. Jumping uses soft recorded cloth, not a rising arcade chirp. Attack swings are quieter than confirmed punch impacts. Quiet hurt grunts alternate recorded takes. Crowd gasps begin at launch force 14; force 17 adds a launch accent. Knockouts replace a gasp with a short cheer. Crowd reactions are global and limited to roughly one every 5.5–6.5 seconds, not every hit.',
'',
'The SFX master defaults to 55%. Voice and crowd submixes default to 65% of SFX. Music defaults to 16%, with a further 0.30 gain to accommodate the original beat’s hot mastering. All sounds pass through a shared compressor (−10 dB threshold, 12:1 ratio, 3 ms attack, 150 ms release) and 0.75 output gain. Footsteps/jumps are over 14 dB quieter in cue gain than contact. Music ducks to 46% briefly on heavy contact, launches and crowd reactions. Sample voices are capped at 12 effects, 3 grunts and 1 crowd recording. Quiet movement cannot evict a higher-priority impact.',
'',
'## Complete cue list',
'',
'Gain is before the SFX master and voice/crowd submix. Variants rotate; no synthesized fallback or generated voice is used. Every one of the 52 moves uses its actual activation event, with the move ID carried to network guests.',
'',
'| Cue | Action | Sample file(s) | Gain | Bus | Minimum interval |',
'| --- | --- | --- | --- | --- | --- |',
...Object.entries(CUES).map(([id,c])=>'| '+[id,c.label,c.samples.map(s=>s+'.mp3').join(', '),c.gain,c.bus,c.cooldown+' ms'].join(' | ')+' |'),
'',
'Recovery replaces the ordinary swing cue; Omen uses a teleport recording. Regent and Vexa use blade recordings; Kairo uses cloth/light and blade/heavy swooshes; Omen uses recorded sci-fi shots. A hit triggers the victim’s voice, not the attacker’s. Grunts have a shared 650 ms per-fighter cooldown. Item throws are distinguished from pickup/catch events; healing and explosions have separate cues. Footsteps follow distance traveled while grounded, not an always-running timer. Fast fall and platform drop get a quiet cloth cue. Gravity-cancel attacks use the dodge plus the appropriate grounded attack; no extra unrelated sound is added. Misses do not play contact or crowd audio. Eliminated, frozen and airborne fighters do not generate footsteps.',
'',
'## Source credits / license record',
'',
'The following effects are existing CC0 recordings. Source pages were checked 2026-09-27. Attribution is retained voluntarily. No Nintendo, Brawlhalla, MultiVersus, announcer imitation, or AI-generated audio is included. Freesound assets use the publicly provided high-quality preview encodings under the recording’s CC0 license.',
'',
...Object.entries(m.sources).map(([id,s])=>'- **'+id+' — '+s.author+'**: ['+s.license+']('+s.url+').'+(s.download?' [Downloaded recording]('+s.download+').':'')),
'',
'CC0 legal text: https://creativecommons.org/publicdomain/zero/1.0/legalcode . Kenney pack license files are preserved in ../licenses/. The male pack offers CC0 as an alternative license; this project selects CC0. AuraVoice is the credited performer in the original recording metadata.',
'',
'## Midnight Loop music — separate rights record',
'',
'The exact 153.62-second MP3 from [Midnight Loop’s pinned source]('+m.music.source+') is copied byte-for-byte. SHA-256: '+m.music.sha256+'. The project owner requested reuse and reports that it is a royalty-free beat; title, artist and license documentation are pending. This file is **not claimed to be CC0**. Add the supplied credit and license terms when the owner finds them. Do not treat this register as a grant of rights to redistribute the music independently.',
'',
'Music loops during the fight, pauses/resumes at the current position, resets on a new match, and stops on leaving the arena or hiding the tab. Menu music is silent unless explicitly auditioned in Settings. A single audio engine is shared across matches, so rematch cannot stack background tracks. Browser gesture unlock happens before asynchronous decoding. Sound failure never prevents playing, and never substitutes an oscillator.',
'',
'## Asset level measurements',
'',
'All sound-effect derivatives are trimmed, have tiny edge fades, and are converted to 44.1 kHz mono MP3 for Safari/Chrome compatibility. Normalization targets −20 dBFS RMS where the −6 dBFS peak ceiling allows; sharp transients deliberately retain their natural crest factor. MP3 re-decoded peaks are validated below −4.5 dBFS. Music is unchanged: its decoded peak is +3.39 dBFS and RMS −9.07 dBFS, which is why runtime attenuation is essential.',
'',
'| Recording | Duration | Decoded peak | Decoded RMS |',
'| --- | --- | --- | --- |',
...m.samples.map(s=>'| '+[s.name,s.duration.toFixed(3)+' s',s.peakDb.toFixed(2)+' dBFS',s.rmsDb.toFixed(2)+' dBFS'].join(' | ')+' |'),
'',
'The [machine-readable manifest](manifest.json) contains original source filenames, source hashes, exact trim positions, gain changes and derivative hashes. scripts/prepare-audio.mjs reproduces conversions using FFmpeg; scripts/fetch-audio-sources.mjs fetches the newly added sources. Existing Kenney packs are from the original asset import. No audio generation occurs.',
'',
'## Verification / listening limits',
'',
'Automated checks cover hashes, source records, measured levels, cue coverage for all 52 moves, cooldowns, mute/submix behavior, network metadata, browser decoding, gesture unlock, pause/resume, rematch, and a four-fighter full-volume mix stress test. These do not replace listening on physical phone speakers or headphones. Settings → Sound Check exposes every runtime cue and the fight music for final listening and personal balance adjustments.',
''];
writeFileSync('public/assets/audio/SOUND-DESIGN.md',text.join('\n')+'\n');
