import {chromium} from 'playwright';import assert from 'node:assert/strict';import {mkdir} from 'node:fs/promises';
await mkdir('work/qa/handheld',{recursive:true});
const browser=await chromium.launch();const base=process.env.QA_URL||'http://localhost:5173/';const errors=[];
async function within(page,selector){const r=await page.locator(selector).boundingBox(),v=page.viewportSize();assert(r&&r.x>=-1&&r.y>=-1&&r.x+r.width<=v.width+1&&r.y+r.height<=v.height+1,selector+' clipped at '+JSON.stringify(v)+' '+JSON.stringify(r));return r;}
try{for(const [width,height] of [[320,568],[375,667],[390,844],[430,932],[768,1024],[844,390],[1280,800]]){
 const context=await browser.newContext({viewport:{width,height},isMobile:width<1000,hasTouch:width<1000});const page=await context.newPage();page.on('pageerror',e=>errors.push(String(e)));await page.goto(base+'?debug');await page.locator('main:not([inert])').waitFor();
 await within(page,'.app-shell');await within(page,'.selection-actions .primary-button');await within(page,'.fighter-picker');
 await page.getByRole('button',{name:'Next fighter',exact:true}).click();assert.equal(await page.getByRole('button',{name:'Select Regent-9',exact:true}).getAttribute('aria-pressed'),'true');await page.getByRole('button',{name:'Previous fighter',exact:true}).click();await page.getByRole('button',{name:'Select Omen Null',exact:true}).click();await page.getByRole('heading',{name:'Omen Null',exact:true}).waitFor();await page.getByRole('button',{name:'Next fighter',exact:true}).click();await page.getByRole('heading',{name:'Kairo Venn',exact:true}).waitFor();
 await page.screenshot({path:`work/qa/handheld/roster-${width}x${height}.png`});await page.getByRole('button',{name:'LET’S PLAY'}).click();await within(page,'.screen-footer .primary-button');await page.getByRole('button',{name:'CHOOSE ARENA'}).click();await within(page,'.screen-footer .primary-button');await page.getByRole('button',{name:'PLAY NOW',exact:true}).click();await page.waitForFunction(()=>window.rift?.simulation?.tick>155,{},{timeout:60000});
 if(width<1000){const pad=await within(page,'.dpad'),dodge=await within(page,'.touch-button.dodge');assert(pad.width>=132);assert(dodge.x+dodge.width/2>width/2,'Dodge must be on right');for(const action of ['jump','light','heavy','dodge','item']){const b=await within(page,'.touch-button.'+action);assert(b.width>=44&&b.height>=44,'Tap target too small');}await within(page,'.deck-utility');
  // Left thumb keeps moving while the right thumb dodges; controls survive HUD renders.
  const cdp=await context.newCDPSession(page);await page.evaluate(()=>{const s=window.rift.simulation;s.actors[0].invulnerable=600;s.actors[0].dodgeCD=0;});const p1={x:pad.x+pad.width*.87,y:pad.y+pad.height*.5,id:1},p2={x:dodge.x+dodge.width/2,y:dodge.y+dodge.height/2,id:2};await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[p1,p2]});await page.waitForTimeout(220);const input=await page.evaluate(()=>window.rift.bridge.input.sample());assert.equal(input.x,1);assert.equal(input.dodge,true);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.equal(await page.evaluate(()=>window.rift.bridge.input.sample().dodge),false);
 }
 await within(page,'.game-screen');await page.screenshot({path:`work/qa/handheld/match-${width}x${height}.png`});console.log('PASS viewport '+width+'x'+height);await context.close();
}assert.deepEqual(errors,[]);}finally{await browser.close();}
