import {chromium,webkit} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
const base=process.env.QA_URL||'http://localhost:5173/';
await mkdir('work/qa/multiplayer',{recursive:true});
const browser=await chromium.launch(),guestBrowser=process.env.QA_GUEST_ENGINE==='webkit'?await webkit.launch():browser,contexts=[],errors=[];
if(guestBrowser!==browser){const probe=await guestBrowser.newPage();const supported=await probe.evaluate(()=>typeof RTCPeerConnection!=='undefined');await probe.close();if(!supported){console.log('SKIP mixed-engine WebRTC: this WebKit build has no RTCPeerConnection. Run lobby-qa.mjs for unsupported-browser fallback coverage.');await guestBrowser.close();await browser.close();process.exit(0);}}
async function phone(engine=browser){const context=await engine.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});contexts.push(context);await context.addInitScript(()=>localStorage.setItem('rift-breakers-settings-v1',JSON.stringify({mute:false})));const page=await context.newPage();page.on('pageerror',e=>errors.push(String(e)));return page;}
async function guest(code,name){const p=await phone(name==='Nova'?guestBrowser:browser);await p.goto(`${base}?debug#room=${code}`);await p.getByRole('textbox',{name:'Player name',exact:true}).fill(name);await p.getByRole('button',{name:'JOIN ROOM',exact:true}).click();await p.getByRole('button',{name:'YOUR PLAYER · NOT READY',exact:true}).waitFor({timeout:30000});await p.getByRole('button',{name:'YOUR PLAYER · NOT READY',exact:true}).click();await p.getByRole('button',{name:'READY TO BRAWL',exact:true}).click();return p;}
try{
 const host=await phone();await host.goto(base+'?debug');await host.getByRole('button',{name:'PLAY FRIENDS',exact:true}).click();await host.getByRole('textbox',{name:'Player name',exact:true}).fill('Captain');await host.getByRole('button',{name:'HOST A ROOM',exact:true}).click();await host.locator('.room-code').waitFor({timeout:30000});const code=await host.locator('.room-code').innerText();assert.match(code,/^[A-Z2-9]{12}$/);assert(await host.getByRole('img',{name:/Scan this QR/}).isVisible());await host.screenshot({path:'work/qa/multiplayer/host-qr.png'});
 const p2=await guest(code,'Nova'),p3=await guest(code,'Comet'),p4=await guest(code,'Orbit');
 await host.getByRole('button',{name:'Players 4/4',exact:true}).click();await host.screenshot({path:'work/qa/multiplayer/four-players.png'});assert(await host.getByRole('button',{name:'START BATTLE',exact:true}).isEnabled());
 const fifth=await phone();await fifth.goto(`${base}?debug#room=${code}`);await fifth.getByRole('textbox',{name:'Player name',exact:true}).fill('Extra');await fifth.getByRole('button',{name:'JOIN ROOM',exact:true}).click();await fifth.getByText('Room full: all four player slots are occupied.',{exact:true}).waitFor({timeout:30000});
 await host.getByRole('button',{name:'START BATTLE',exact:true}).click();for(const p of [host,p2,p3,p4])await p.waitForFunction(()=>window.rift?.simulation.tick>180,{},{timeout:60000});
 for(const p of [host,p2,p3,p4]){await p.waitForFunction(()=>window.rift.bridge.audio.status.musicPlaying&&window.rift.bridge.audio.status.loaded===39);assert.deepEqual(await p.evaluate(()=>window.rift.bridge.audio.status.failures),[]);}
 assert.deepEqual(await Promise.all([host,p2,p3,p4].map(p=>p.evaluate(()=>window.rift.bridge.localIndex))),[0,1,2,3]);
 await host.evaluate(()=>window.rift.bridge.network.peer.disconnect());await host.waitForFunction(()=>!window.rift.bridge.network.peer.disconnected);assert.equal(await host.evaluate(()=>window.rift.bridge.network.state.members.length),4);assert.equal(await host.evaluate(()=>window.rift.bridge.network.state.phase),'playing');
 // Inputs cross real WebRTC data channels; guests never independently resolve combat.
 await host.evaluate(()=>{window.rift.simulation.actors.forEach(a=>{a.invulnerable=600;a.x=330+a.id*70;a.y=610;a.vx=0;a.vy=0;});});await p2.waitForTimeout(150);
 const x=await host.evaluate(()=>window.rift.simulation.actors[1].x);await p2.evaluate(()=>window.rift.bridge.input.press(901,'right'));await p2.waitForTimeout(220);await p2.evaluate(()=>window.rift.bridge.input.release(901));assert(await host.evaluate(()=>window.rift.simulation.actors[1].x)>x+25,'Guest moves its assigned fighter on host');
 await host.getByRole('button',{name:'Pause match',exact:true}).click();await p2.waitForTimeout(200);assert(await p2.evaluate(()=>window.rift.bridge.network.hostPaused));const tick=await host.evaluate(()=>window.rift.simulation.tick);await p2.waitForTimeout(150);assert.equal(await host.evaluate(()=>window.rift.simulation.tick),tick);await host.getByRole('button',{name:'RESUME',exact:true}).click();
 await host.evaluate(()=>{const s=window.rift.simulation;s.spawnItem('spike');const item=s.items.at(-1);item.heldBy=1;item.owner=1;s.actors[1].held=item.id;});await p2.waitForFunction(()=>!document.querySelector('.touch-button.item')?.disabled);await p2.getByRole('button',{name:'Z THROW',exact:true}).tap();await host.waitForFunction(()=>window.rift.simulation.actors[1].held===null);await p2.getByRole('button',{name:'X JUMP',exact:true}).tap();await host.waitForFunction(()=>window.rift.simulation.actors[1].y<590);
 for(const p of [host,p2,p3,p4])await p.waitForFunction(()=>window.rift.bridge.audio.played.throw===1&&window.rift.bridge.audio.played.jump>=1);
 await p2.screenshot({path:'work/qa/multiplayer/guest-match.png'});
 await p4.close();await host.waitForFunction(()=>window.rift.bridge.network.state.members[3].cpu,{},{timeout:15000});
 // End authoritatively; all remaining clients must agree on winners and results.
 await host.evaluate(()=>{const s=window.rift.simulation;for(const a of s.actors.slice(1)){a.stocks=1;a.x=1300;a.invulnerable=0;}});
 await host.getByRole('button',{name:'REMATCH LOBBY',exact:true}).waitFor({timeout:15000});await p2.getByText('Waiting for the host to reopen the lobby.',{exact:true}).waitFor({timeout:15000});await host.getByRole('button',{name:'REMATCH LOBBY',exact:true}).click();await p2.getByRole('button',{name:'YOUR PLAYER · NOT READY',exact:true}).waitFor();
 for(const p of [p2,p3]){await p.getByRole('button',{name:'YOUR PLAYER · NOT READY',exact:true}).click();await p.getByRole('button',{name:'READY TO BRAWL',exact:true}).click();}await host.getByRole('button',{name:'START BATTLE',exact:true}).click();for(const p of [host,p2,p3])await p.waitForFunction(()=>window.rift?.simulation.tick>180&&window.rift.simulation.tick<500&&window.rift.bridge.network.state.phase==='playing',{},{timeout:60000});
 const nextX=await host.evaluate(()=>window.rift.simulation.actors[1].x);await p2.evaluate(()=>window.rift.bridge.input.press(902,'left'));await p2.waitForTimeout(180);await p2.evaluate(()=>window.rift.bridge.input.release(902));assert(await host.evaluate(()=>window.rift.simulation.actors[1].x)<nextX-20,'Guest input sequence resets on rematch');
 await host.getByRole('button',{name:'Pause match',exact:true}).click();await host.getByRole('button',{name:'Leave room',exact:true}).click();await p2.getByRole('heading',{name:'SIGNAL LOST.',exact:true}).waitFor({timeout:15000});
 assert.deepEqual(errors,[]);console.log('PASS: recorded music and shared jump/throw audio on all four devices; public signaling + real WebRTC, QR/deep link, four named humans, fifth-player rejection, input/throw ownership, touch jump, shared pause/results, CPU takeover, playable second round, signaling reconnect and host disconnect.');
}finally{await Promise.all(contexts.map(c=>c.close()));await browser.close();if(guestBrowser!==browser)await guestBrowser.close();}
