import {chromium,webkit} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
const base=process.env.QA_URL||'http://localhost:5173/';
await mkdir('work/qa/multiplayer',{recursive:true});
const browser=await chromium.launch(),guestBrowser=process.env.QA_GUEST_ENGINE==='webkit'?await webkit.launch():browser,contexts=[],errors=[];
if(guestBrowser!==browser){const probe=await guestBrowser.newPage();const supported=await probe.evaluate(()=>typeof RTCPeerConnection!=='undefined');await probe.close();if(!supported){console.log('SKIP mixed-engine WebRTC: this WebKit build has no RTCPeerConnection. Run lobby-qa.mjs for unsupported-browser fallback coverage.');await guestBrowser.close();await browser.close();process.exit(0);}}
async function phone(engine=browser){const context=await engine.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});contexts.push(context);await context.addInitScript(()=>localStorage.setItem('rift-breakers-settings-v1',JSON.stringify({mute:false})));const page=await context.newPage();page.on('pageerror',e=>errors.push(String(e)));return page;}
async function guest(code,name){const p=await phone(name==='Nova'?guestBrowser:browser);await p.goto(`${base}?debug#room=${code}`);await p.getByRole('textbox',{name:'Player name',exact:true}).fill(name);await p.getByRole('button',{name:'JOIN ROOM',exact:true}).click();await p.getByRole('button',{name:'YOUR PLAYER · NOT READY',exact:true}).waitFor({timeout:30000});await p.getByRole('button',{name:'YOUR PLAYER · NOT READY',exact:true}).click();await p.getByRole('button',{name:'READY TO BRAWL',exact:true}).click();return p;}
try{
 const host=await phone();await host.goto(base+'?debug');await host.getByRole('button',{name:'PLAY FRIENDS',exact:true}).click();await host.getByRole('textbox',{name:'Player name',exact:true}).fill('Captain');await host.getByRole('button',{name:'HOST A ROOM',exact:true}).click();await host.locator('.room-code').waitFor({timeout:30000});const code=await host.locator('.room-code').innerText();assert.match(code,/^[A-Z2-9]{12}$/);assert(await host.getByRole('img',{name:/Scan this QR/}).isVisible());await host.screenshot({path:'work/qa/multiplayer/host-qr.png'});
 await host.getByRole('button',{name:'rules',exact:true}).click();await host.getByRole('combobox',{name:'Arena',exact:true}).selectOption('neon-foundry');
 const p2=await guest(code,'Nova'),p3=await guest(code,'Comet'),p4=await guest(code,'Orbit');
 await host.getByRole('button',{name:'Players 4/4',exact:true}).click();await host.screenshot({path:'work/qa/multiplayer/four-players.png'});assert(await host.getByRole('button',{name:'START BATTLE',exact:true}).isEnabled());
 const fifth=await phone();await fifth.goto(`${base}?debug#room=${code}`);await fifth.getByRole('textbox',{name:'Player name',exact:true}).fill('Extra');await fifth.getByRole('button',{name:'JOIN ROOM',exact:true}).click();await fifth.getByText('Room full: all four player slots are occupied.',{exact:true}).waitFor({timeout:30000});
 await host.getByRole('button',{name:'START BATTLE',exact:true}).click();for(const p of [host,p2,p3,p4])await p.waitForFunction(()=>window.rift?.simulation.tick>180,{},{timeout:60000});
 for(const p of [host,p2,p3,p4]){assert.equal(await p.evaluate(()=>window.rift.simulation.config.stage),'neon-foundry');await p.waitForFunction(()=>window.rift.bridge.audio.status.musicPlaying&&window.rift.bridge.audio.status.loaded===39);assert.deepEqual(await p.evaluate(()=>window.rift.bridge.audio.status.failures),[]);}
 assert.deepEqual(await Promise.all([host,p2,p3,p4].map(p=>p.evaluate(()=>window.rift.bridge.localIndex))),[0,1,2,3]);
 await host.evaluate(()=>window.rift.bridge.network.peer.disconnect());await host.waitForFunction(()=>!window.rift.bridge.network.peer.disconnected);assert.equal(await host.evaluate(()=>window.rift.bridge.network.state.members.length),4);assert.equal(await host.evaluate(()=>window.rift.bridge.network.state.phase),'playing');
 // Inputs cross real WebRTC data channels; guests never independently resolve combat.
 await host.evaluate(()=>{window.rift.simulation.actors.forEach(a=>{a.invulnerable=600;a.x=330+a.id*70;a.y=window.rift.simulation.stage.platforms[0].y;a.vx=0;a.vy=0;});});await p2.waitForTimeout(150);
 const x=await host.evaluate(()=>window.rift.simulation.actors[1].x);await p2.evaluate(()=>window.rift.bridge.input.press(901,'right'));await p2.waitForTimeout(220);await p2.evaluate(()=>window.rift.bridge.input.release(901));assert(await host.evaluate(()=>window.rift.simulation.actors[1].x)>x+25,'Guest moves its assigned fighter on host');
 await host.getByRole('button',{name:'Pause match',exact:true}).click();await p2.waitForTimeout(200);assert(await p2.evaluate(()=>window.rift.bridge.network.hostPaused));const tick=await host.evaluate(()=>window.rift.simulation.tick);await p2.waitForTimeout(150);assert.equal(await host.evaluate(()=>window.rift.simulation.tick),tick);await host.getByRole('button',{name:'RESUME',exact:true}).click();
 await host.evaluate(()=>{const s=window.rift.simulation;s.spawnItem('spike');const item=s.items.at(-1);item.heldBy=1;item.owner=1;s.actors[1].held=item.id;});await p2.waitForFunction(()=>!document.querySelector('.touch-button.item')?.disabled);await p2.getByRole('button',{name:'Z THROW',exact:true}).tap();await host.waitForFunction(()=>window.rift.simulation.actors[1].held===null);await p2.getByRole('button',{name:'X JUMP',exact:true}).tap();await host.waitForFunction(()=>window.rift.simulation.actors[1].y<590);
 for(const p of [host,p2,p3,p4])await p.waitForFunction(()=>window.rift.bridge.audio.played.throw===1&&window.rift.bridge.audio.played.jump>=1);
 await p2.screenshot({path:'work/qa/multiplayer/guest-match.png'});
 // Combo taps travel through real guest input mailboxes; clients only render host results.
 await host.evaluate(()=>{const {simulation:s,bridge}=window.rift;bridge.paused=true;s.projectiles=[];s.items=[];s.actors.forEach((a,i)=>Object.assign(a,{x:i===1?450:i===0?505:710+i*35,px:i===1?450:i===0?505:710+i*35,y:s.stage.platforms[0].y,py:s.stage.platforms[0].y,vx:0,vy:0,face:i===1?1:-1,grounded:true,damage:0,move:null,chainQueued:null,moveTick:0,stun:0,freeze:0,invulnerable:0,dodgeTime:0,history:[],buffers:{},previous:{x:0,y:0,jump:false,light:false,heavy:false,dodge:false,item:false}}));});
 const comboStep=async(count=1)=>host.evaluate(count=>{const {simulation:s,bridge,scene}=window.rift,z={x:0,y:0,jump:false,light:false,heavy:false,dodge:false,item:false},events=[];for(let i=0;i<count;i++){s.step(z,bridge.network.inputs(z));s.events.forEach(e=>scene.effect(e));events.push(...s.events);}bridge.onUpdate(s);bridge.network.lastPublish=0;bridge.network.publish(s,events,true);},count);
 const comboUntil=async(condition)=>{for(let n=0;n<100;n++){if(await host.evaluate(condition=>{const a=window.rift.simulation.actors[1];return condition==='active'?a.move&&a.moveTick>=a.move.startup:a.move?.id===condition;},condition))return;await comboStep();}throw Error('Network combo never reached '+condition);};
 for(const stage of ['nl','l2','l3']){
  await p2.getByRole('button',{name:'B LIGHT',exact:true}).tap();await p2.waitForTimeout(80);await comboStep();await comboUntil(stage);await comboUntil('active');
  for(const p of [host,p2,p3,p4])await p.waitForFunction(stage=>window.rift.simulation.actors[1].move?.id===stage,stage);
 }
 for(let n=0;n<12&&!(await host.evaluate(()=>window.rift.simulation.actors[1].history.includes('l3')));n++)await comboStep();
 assert.deepEqual(await host.evaluate(()=>window.rift.simulation.actors[1].history),['nl','l2','l3']);
 await p2.locator('.combo-status[data-step="3"]').waitFor();await p2.screenshot({path:'work/qa/multiplayer/guest-combo.png'});
 await host.evaluate(()=>{window.rift.bridge.paused=false;});
 // A guest's real dodge tap must protect on the host and replicate its confirmed evade.
 await host.evaluate(()=>{const {simulation:s,scene,bridge}=window.rift;s.projectiles=[];s.items=[];s.actors.forEach((a,i)=>Object.assign(a,{x:350+i*65,y:s.stage.platforms[0].y,px:350+i*65,py:s.stage.platforms[0].y,vx:0,vy:0,stun:0,freeze:0,move:null,grounded:true,invulnerable:0,dodgeTime:0,dodgeCD:0}));for(const r of [window.rift]){r.evadesSeen=0;const effect=scene.effect.bind(scene);scene.effect=e=>{if(e.kind==='evade')r.evadesSeen++;effect(e);};}});
 for(const p of [p2,p3,p4])await p.evaluate(()=>{const r=window.rift,effect=r.scene.effect.bind(r.scene);r.evadesSeen=0;r.scene.effect=e=>{if(e.kind==='evade')r.evadesSeen++;effect(e);};});
 await p2.getByRole('button',{name:'Y DODGE',exact:true}).tap();await host.waitForFunction(()=>window.rift.simulation.actors[1].dodgeTime>0);
 await host.evaluate(()=>{const {simulation:s,bridge,scene}=window.rift,a=s.actors[0],b=s.actors[1];bridge.paused=true;s.events=[];s.stepActor(a,{x:0,y:0,jump:false,light:true,heavy:false,dodge:false,item:false});a.moveTick=a.move.startup;a.face=1;a.x=b.x-a.move.hitbox.x;a.y=b.y;s.resolveAttack(a);s.events.forEach(e=>scene.effect(e));bridge.network.lastPublish=0;bridge.network.publish(s,s.events,true);a.move=null;});
 for(const p of [host,p2,p3,p4]){await p.waitForFunction(()=>window.rift.evadesSeen===1);assert.equal(await p.evaluate(()=>window.rift.simulation.actors[1].damage),0);assert(await p.evaluate(()=>window.rift.simulation.actors[1].dodgeTime>0));}
 await host.evaluate(()=>{window.rift.bridge.paused=false;});
 await p4.close();await host.waitForFunction(()=>window.rift.bridge.network.state.members[3].cpu,{},{timeout:15000});
 // End authoritatively; all remaining clients must agree on winners and results.
 await host.evaluate(()=>{const s=window.rift.simulation;for(const a of s.actors.slice(1)){a.stocks=1;a.x=1300;a.invulnerable=0;}});
 await host.getByRole('button',{name:'REMATCH LOBBY',exact:true}).waitFor({timeout:15000});await p2.getByText('Waiting for the host to reopen the lobby.',{exact:true}).waitFor({timeout:15000});await host.getByRole('button',{name:'REMATCH LOBBY',exact:true}).click();await p2.getByRole('button',{name:'YOUR PLAYER · NOT READY',exact:true}).waitFor();
 for(const p of [p2,p3]){await p.getByRole('button',{name:'YOUR PLAYER · NOT READY',exact:true}).click();await p.getByRole('button',{name:'READY TO BRAWL',exact:true}).click();}await host.getByRole('button',{name:'START BATTLE',exact:true}).click();for(const p of [host,p2,p3])await p.waitForFunction(()=>window.rift?.simulation.tick>180&&window.rift.simulation.tick<500&&window.rift.bridge.network.state.phase==='playing',{},{timeout:60000});
 // Isolate input transport from CPU attacks and await displacement instead of timing browser scheduling.
 await host.evaluate(()=>{const s=window.rift.simulation;s.actors.forEach((a,i)=>Object.assign(a,{x:230+i*150,y:s.stage.platforms[0].y,vx:0,vy:0,grounded:true,platform:0,move:null,stun:0,freeze:0,invulnerable:600}));});
 for(const p of [host,p2,p3])assert.equal(await p.evaluate(()=>window.rift.simulation.config.stage),'neon-foundry');
 const nextX=await host.evaluate(()=>window.rift.simulation.actors[1].x);await p2.evaluate(()=>window.rift.bridge.input.press(902,'left'));try{await host.waitForFunction(x=>window.rift.simulation.actors[1].x<x-20,nextX,{timeout:3000});}finally{await p2.evaluate(()=>window.rift.bridge.input.release(902));}
 await host.getByRole('button',{name:'Pause match',exact:true}).click();await host.getByRole('button',{name:'Leave room',exact:true}).click();await p2.getByRole('heading',{name:'SIGNAL LOST.',exact:true}).waitFor({timeout:15000});
 assert.deepEqual(errors,[]);console.log('PASS: Neon Foundry geometry synchronized across all four clients; guest three-hit combo synchronized across all four devices; guest dodge protection and confirmed evade synchronized across all four devices; recorded music and shared jump/throw audio on all four devices; public signaling + real WebRTC, QR/deep link, four named humans, fifth-player rejection, input/throw ownership, touch jump, shared pause/results, CPU takeover, playable second round, signaling reconnect and host disconnect.');
}finally{await Promise.all(contexts.map(c=>c.close()));await browser.close();if(guestBrowser!==browser)await guestBrowser.close();}
